### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by s0ggx** [HeDeAnTheonlyone/Death-Point-Teleport#1]
this isnt working for me :( not sure if its from my other mods, could def be that, im using Inventorio which does change how the off hand works, maybe theres a way to make them compatible? 

Love this idea/pack 👍 🥇

**Comment by HeDeAnTheonlyone** [comment]
I'll look into the mod and try to make them compatible.

**Comment by HeDeAnTheonlyone** [comment]
I only found 1.20.1 versions of the mod. Are you not using 1.20.2? If so, then you can't use Death-Point-Teleport. It requires some 
new 1.20.2 features.

**Comment by s0ggx** [comment]
i was in 1.20.1
